permalink: /:year/:month/:title/
markdown: kramdown
theme: null
excerpt_separator: //description
exclude:
  - "Gemfile*"
  - Rakefile
  - vendor/
  - _site/
  - mail/
  - ".*"
include:
  - _headers
env: production
sass:
  sass_dir: css
  style: compressed
