title: Carlgo11.com
url: "carlgo11.com"
permalink: /:year/:month/:title/
markdown: kramdown
img: /img/lain.png
excerpt_separator: //description
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - vendor
  - mail
  - .gitignore
  - .editorconfig
  - .idea
env: production
