permalink: /:year/:month/:title/
markdown: kramdown
kramdown:
  hard_wrap: true
theme: null
excerpt_separator: //description
exclude:
  - "Gemfile*"
  - Rakefile
  - vendor/
  - _site/
  - mail/
  - ".*"
include:
  - _headers
env: development
sass:
  sass_dir: css
  style: compressed
