permalink: /:year/:month/:title/
markdown: kramdown
author: Carlgo11
kramdown:
  hard_wrap: true
theme: null
excerpt_separator: "#"
social_image: https://repository-images.githubusercontent.com/194316044/3de72580-a905-11e9-8dfc-563d74bbb052
exclude:
  - "Gemfile*"
  - Rakefile
  - vendor/
  - _site/
  - mail/
  - ".*"
include:
  - _headers
env: development
sass:
  sass_dir: css
  style: compressed
